### ISSUE TITLE
Loop Kaybind

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#15]
I use this update for 1 sec and i see issue. Seriously man? Loop on ESCAPE? every time i open pause menu i change this unintentionally. Leave this unbound or find another key to bind please XD

**Comment by Anoaxx** [comment]
I was thinking you resting from project right now??

**Comment by charlyb01** [comment]
I commited it 5 days ago when you told me but I didn't release a new version so I didn't push it. As I think I won't have a lot of time in the future, I preferred to release a version without this "bug" if new people install it during my break x)
I got a bit of time this evening so I pushed a few changes that I've made in my mods

**Comment by Anoaxx** [comment]
Btw in options of mod you can choose default category you know, and its "overworld" not "default" ><

**Comment by charlyb01** [comment]
The default category at start means "which category should I try to play when I run the game". So by default, this config is set to Overworld, but you can set it to Default. The Default category is the category that doesn't use my category system to play music but the vanilla one, that's why the base config of the mod is set to Overworld (a category that I've made) instead of Default (the vanilla category). I know I keep using the word "default" so I may have confused you but I hope it's clearer now =)
