### ISSUE TITLE
Changig music so fast

### ISSUE THREAD

**Issue by barraIhsan** [sf-inc/music_control#4]
So, when BEFORE i enter my world I turn my music to 0% then I enter the world. Suddenly it says changing the music (BUT ITS REALLY FAST) its also cause performance issue
Screenshot :
![image](https://user-images.githubusercontent.com/57800056/113363117-3b975a00-937a-11eb-99b7-aed791dd8249.png)
Video :

https://user-images.githubusercontent.com/57800056/113363196-75686080-937a-11eb-8a88-26aa58fe92d0.mp4

**Comment by charlyb01** [comment]
What do you mean "but it's really fast"? I'll check this this weekend (as your other issue)

**Comment by barraIhsan** [comment]
No i didnt press any key. I just joined with music turned off and suddenly like that

**Comment by charlyb01** [comment]
What other mods installed do you have?

**Comment by barraIhsan** [comment]
![image](https://user-images.githubusercontent.com/57800056/113414383-11c84c80-93e7-11eb-93ac-c33300b51ced.png)
Its a lot... But i think I **might** have tried using only this mod, and the bug still appear

**Comment by charlyb01** [comment]
So yeah, this is definitely not coming from my mod: neither the performance issue, nor the spam click without touching key. I will check some of the mods you installed. There are only two possible explanations: another mod is doing something weird, or you have a keyboard issue (like it's pressing keys by itself). Also, you should check if there are no mods using the same keybind as my mod, which could be the source of lag if your keyboard press keys without your permission.

**Comment by charlyb01** [comment]
Maybe try without TooManyBinds, or change my mod keybinds.... I don't know what's your problem but if you have only my mod you shouldn't have this problem (and I've tried my mods with 100+ mods and I never got any problem for my mod).
Tell me if you still have this problem with what I said to try

**Comment by barraIhsan** [comment]
> Maybe try without TooManyBinds, or change my mod keybinds.... I don't know what's your problem but if you have only my mod you shouldn't have this problem (and I've tried my mods with 100+ mods and I never got any problem for my mod).
> Tell me if you still have this problem with what I said to try

I think it try with only this mod, and still happened. Wait I think you didn't understand how to reproduce it
1. Save & Quit (If you are in singleplayer)
2. Change the `Music` to 0% in `Options > Music & Sounds`
3. Enter the world
4. Bug happened

**Comment by charlyb01** [comment]
You keep saying "I think" as is you didn't try again while I asked you... Because I did try everything you said and the but never happened. When you out the music to 0% it doesn't change anything, you still can change music with keybinds but you won't hear it. If you see that it changes a lot of times music, it means that the keybind is pressed so it's either your keyboard, or another mod that do some weird thing (maybe with keybinds), as I already told you

**Comment by barraIhsan** [comment]
![image](https://user-images.githubusercontent.com/57800056/113572045-aaf29f80-9641-11eb-884d-7e7a5c662209.png)
Ok, so this is my `.minecraft/mods` folder (with some folder inside that is for mods that unused). And its still like the video I sent in
![image](https://user-images.githubusercontent.com/57800056/113572124-dd040180-9641-11eb-98bf-4b7d1148c03a.png)
This is my Music and sounds setting
So when I change the master volume to like 1% it not gonna change the music so fast
BUT when I change it again to 0% the bug appears again.
Is there the fabric API is outdated, or the music control outdated.

**Comment by charlyb01** [comment]
Alllllright, with this configuration the mod tries to play music while the master is off. And it spams every tick because I guess you changed the default config so that there is no time without music, am I right? Thanks for your patience. I'll see what I can do, I guess next week I'll publish a version that fix it and that add possibility to play custom musics ;)
If it's not out out next week, don't worry I won't forget you

**Comment by barraIhsan** [comment]
ok, thanks!
