### ISSUE TITLE
How does music disc work with the mod?

### ISSUE THREAD

**Issue by alien-sunset** [sf-inc/music_control#40]
put a disc in and let the vanilla notification fade, then hit the print music keybind, it says no music playing or lists the background music that was playing before the disc was inserted.

if there was no background music playing before the disc was inserted the pause button will pause the disc, if background music is playing it will play the disc OVER the background music and the pause button will pause both.

oop forgot versions:
minecraft 1.20.1 
mod version: 1.6.2+1.20.1

**Comment by charlyb01** [comment]
Hello,

This is how Minecraft works. In Minecraft, sounds are handled in different canals to be able to change the volume of music and mobs separately for example. It's the same with music discs, that are in their own canal, as they are in-game music (relative to player position). Playing a music disc has always been able to play while background music is playing for this reason.

About my mod, it specifies that it handles only background music, so playing a music in a jukebox will print the music of the jukebox, but if you hit the print button, it will print the background music, if there is one playing. It displays the same way just because I found it nice, but you can change the display method in the mod config for less confusion.  
Finally, the fact that the pause button pauses all sounds is known, this is the expected behavior for now. This is a feature request that is in my to-do list: to pause only background music, as this is the only kind of sound we want to handle. I'll add an issue, I thought there was already one.

Hope that's clear now, don't hesitate to reopen the issue if needed =)
