### ISSUE TITLE
cant start on quilt 1.20.1 

### ISSUE THREAD

**Issue by alec-jensen** [sf-inc/music_control#52]
https://mclo.gs/4AcLu8x
only happens with latest version, version 1.6.3+1.20.1 works fine

**Comment by Anoaxx** [comment]
99% of mods that are for Fabric should work on Quilt, but its not stated that all of them are gonna work and author is not stating its gonna work on it. Even tho it was working on 1.6.3 of the mod on 1.20.1 with Quilt loader theres 0% chance that if u change any of that circustances its still gonna work. Author is not familiar with Quilt ecosystem, as they stated in #47 issue of mine. 

So at the end of the day u have some solutions to not feel lefted out: 1. U can stay on 1.6.3 version of a mod. 2. U can change minecraft version and test if its gonna work there. 3. U can change the version of Quilt and see if thats gonna work. 4. U can consider swithing to Fabric, cause theres nota lot mods that are Quilt exclusive(i did that, and since then i dont have any problems with mod or other mods that are not stated that have a version for quilt or are gonna work on quilt. Tbh after my extensive searching i didnt find more then 3 mods that are Quilt exclusive, Effective that brings minecraft trailer water behaviour. thats cool, but theres other mods that are bring some funcionality of a mods such as Wakes or Dynamic Surroundings(or not released for 1.20.1 yet Mambience(but it is on 1.20.4 which is weird but shush), Better Grass mod that u can replace with some textures and its not working well with not default textures on fancy setting or with overlay textures on the classic and fancy setting, and Inspecio that is a mod for tooltips that i believe some other mods have similar or the same funcionality. And theres not much more there at least i think so you chould consider switching. 


For the developer of a mod theres simple solution if they wants to repair the problem. Get familiar with quilt. Sit down and test whats wrong with code on newer versions then 1.6.3 and change it that way funcionality would stay the same or if u cant then turn that funcionality for quilt until better solution shows up. I would highly reccomand you to use it with other mods, prolly some bigger modpack cause when i was doing the tests, sometimes mod was working and sometimes not. Like everything was fine on my 100 mods pack until i added some new mod that was breaking the game, but using it alone wasnt causing the crash. Maybe its a conflict of some sort with other mods in Quilt enviroment but idk actually, and to be more insightful: No i dont know which mods in combination were causing a problem, sometimes they werent even connected to music or controling the sounds, they sometimes even not adding any new sounds... Its Quilt specific, and its about Music Control. I just now thought that it was working before cause i was on 1.6.3 of a mod, and then switched to newer version cause i was updating it in between modding my game so my words could not be truthfull at all. Althtough *MY GAME NEVER CRASHED ON V1.7/1.7.1 OF THE MOD ON 1.20.1 ON FABRIC LOADER*

**Comment by charlyb01** [comment]
Hello and thanks for your report.

As @Anoaxx said, I've never mentioned it should work on Quilt, as I'm not testing it in my development environment. However, I don't see any reason why it shouldn't, so I'll take a brief look tomorrow and get back to you. This doesn't mean that future versions will work of course.

**Comment by charlyb01** [comment]
Hello, I investigated a bit more and it seems that the Quilted Fabric API doesn't contain the bit of code I'm now using in newer version of Music Control. This change was necessary to fix important issues, so I won't be able to update it to support Quilt, for now at least. Sorry, but I guess you could use the Fabric loader instead if you really want to play with this mod, as most mods are Fabric and not Quilt I believe

**Comment by Anoaxx** [comment]
> I'm getting rid of this code

Wdym? this part of a mod is not going to be in a mod or you need to rewrite it?

**Comment by charlyb01** [comment]
@Anoaxx I don't need it anymore, I rewrote it if you prefer
