### ISSUE TITLE
Music Title + Author[request]

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#8]
_PROBLEM_
If i use this mod, and music is printed is printed as location in system

_SOLUTION_
Just do something like vanilla when jukebox starts playing. 

If you do you can do this option turn on by default.

**Comment by charlyb01** [comment]
That's a good idea, I'll see if it's possible. For music discs, we already know it is but the other ones may not be named sadly. I'll check that

**Comment by Anoaxx** [comment]
> but the other ones may not be named sadly

Then let it show the filename, or as now, the path.

**Comment by Anoaxx** [comment]
Another request: Add option to print song name in toast and chat

**Comment by charlyb01** [comment]
What's wrong with the current print system? And I'm sorry but what is "in toast"?

**Comment by Anoaxx** [comment]
advensments and recipes are show in "Toasts" a little box appear in up right corner. 

and is nothing wrong with current print system, but option to have it on chat or in toasts is a good bonus ;)

**Comment by charlyb01** [comment]
Oh okay I see. Well I guess you're right, more options can be good =)

**Comment by charlyb01** [comment]
If you're crazy enough, you could find the title of every music in Minecraft and tell it to me so that I can add it to the lang file of the mod. But if not it's okay, I may do it myself one day when I have free time =D
Because yes, I'm sad to tell you that Minecraft songs' title are not stored anywhere (except for discs)
