### ISSUE TITLE
More categories at once[request/question]

### ISSUE THREAD

**Issue by Anoaxx** [sf-inc/music_control#9]
_PROBLEM_ 
If I have mod like Charmonium or Atmosfera im able to hear music from it if i don't change category? If don't, can you add option to play songs from more then one category? something like vanilla + custom(because this mods have built-in resource packs). Im don't know i understand correctly your mod. If im not in the "player control" mode (creative or cheat on survival) im still gonna hear songs as they play in vanilla + resource packs? Because description doesn't seem to (heh) describe this.

**Comment by charlyb01** [comment]
Hmm well I didn't think about that, you're right. Currently, you can't change category in survival (except if you enable cheat) because categories are linked to dimensions. So there is something stupid, without cheat you can't play these custom musics from customs dimensions for now. Moreover as you noticed, some mods add musics to existing dimensions too, so these are two things I didn't think about. 
I guess I just need to enable the switch between current category and custom category when not using cheat. I will try to do more by adding custom musics from resourcepacks/mods to appropriate dimension's category but to do so the resourcepack/mod need to use explicit names, that indicates where should be played (I looked into Charmonium and it's okay with them at least, that's how I got the idea).
Thanks a lot for the suggestion (and the other ones, I'll read them carefully), just be a bit patient about updates
